baseURL: "https://bensonkitia.com"
copyright: Benson V.K.
languageCode: en-us
timeZone: America/Chicago
title: bk;
author:
  name: Benson Kitia
  email: benson@kitia.dev
  twitter: "@bensonkitia"
menu:
  main:
    - name: All Writings
      url: /writings
      weight: 1
    - name: Colophon
      url: /colophon
      weight: 1
    - name: Projects
      url: /projects
      weight: 1
    - name: Subscribe
      url: /subscribe
      weight: 1
params:
  description: Benson Kitia is a builder; designer & developer in Chicago.
  title: bk; by Benson Kitia
  twitter: "@bensonkitiacom"
  icon: https://bensonkitia.com/images/icon.png
