baseURL: "https://www.kitia.net"
copyright: Ben Kitia
languageCode: en-us
timeZone: America/Chicago
title: Ben Kitia
description: Ben Kitia is a Chicago-based software builder who's the founder and Emcee (CEO) of Helianth and TaleSuite.
uglyURLs: true

menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Blog
      url: /blog
      weight: 1
    - name: Subscribe
      url: /subscribe
      weight: 1

outputs:
  home:
    - HTML
    - RSS
  RSS:
    mediatype: "application/rss"
    baseName: "feed"
    isPlainText: true
    notAlternative: true

permalinks:
  publ: /:title/

params:
  author:
    name: Ben Kitia
    twitter: "benkitia"
  description: Ben Kitia is a Chicago-based developer and tech entrepreneur who's the founder and  CEO of Helianth
  wordmark: BK
  title: Ben Kitia
  twitter: "@benkitia"
  icon: https://www.kitia.net/images/icon.png
  mastodon: mastodon.social/@kitia

sitemap:
  changefreq: always
  filename: sitemap.xml
  priority: 1
