baseURL: "https://www.kitia.net"
copyright: Ben Kitia
languageCode: en-us
timeZone: America/Chicago
title: Ben Kitia
description: Ben Kitia is a Chicago-based software builder who's the founder and Emcee (CEO) of Pubnent.
author:
  name: Ben Kitia
  email: ben@kitia.net
  twitter: "benkitia"
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Blog
      url: /blog
      weight: 1
    - name: Subscribe
      url: /subscribe
      weight: 1
outputs:
  RSS:
    mediaType: application/rss+xml
    baseName: /feed.rss
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
  home:
    - HTML
    - RSS
permalinks:
  publ: /:title/
params:
  description: Ben Kitia is a Chicago-based software builder who's the founder and Emcee (CEO) of Pubnent.
  wordmark: BK
  title: Ben Kitia
  twitter: "@benkitia"
  icon: https://www.kitia.net/images/icon.png
  mastodon: mastodon.social/@kitia
