baseURL: "https://bensonkitia.com"
copyright: Benson Kitia
languageCode: en-us
timeZone: America/Chicago
title: Benson Kitia
author:
  name: Benson Kitia
  email: hello@bvk.email
  twitter: "bensonkitia"
menu:
  main:
    - name: Archive
      url: /blog
      weight: 1
    - name: Colophon
      url: /colophon
      weight: 1
    - name: Projects
      url: /projects
      weight: 1
    - name: Subscribe
      url: /subscribe
      weight: 1
outputs:
  home:
    - HTML
    - RSS
params:
  description: Benson Kitia is a builder; designer & developer in Chicago.
  wordmark: BK
  title: Benson Kitia
  twitter: "@bensonkitiacom"
  icon: https://bensonkitia.com/images/icon.png
  goatCounter: analytics.bensonkitia.com
