baseURL = 'https://bensonkitia.com'
languageCode = 'en-us'
title = 'bk;'
copyright = "Benson V.K."
author = "Benson Kitia"
seoImage = "https://i.imgur.com/Mg5YbdS.png"
microAnalyticsId = "ZwSg9rf6GA"

[[menu.main]]
name = "All Writings"
url = "/writings"
weight = 1
[[menu.main]]
name = "Colophon"
url = "/colophon"
weight = 1
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 1
[[menu.main]]
name = "Subscribe"
url = "/subscribe"
weight = 1