baseURL = 'https://bensonkitia.com'
copyright = "Benson V.K."
languageCode = 'en-us'
timeZone = "America/Chicago"
title = 'bk;'

[author]
name = "Benson Kitia"
email = "benson@kitia.dev"
twitter = "bensonkitia"

[[menu.main]]
name = "All Writings"
url = "/writings"
weight = 1
[[menu.main]]
name = "Colophon"
url = "/colophon"
weight = 1
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 1
[[menu.main]]
name = "Subscribe"
url = "/subscribe"
weight = 1