baseURL: "https://bensonkitia.com"
copyright: Ben Kitia
languageCode: en-us
timeZone: America/Chicago
title: Ben Kitia
author:
  name: Ben Kitia
  email: hello@bvk.email
  twitter: "benkitia"
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Blog
      url: /blog
      weight: 1
    - name: Projects
      url: /projects
      weight: 1
    - name: Subscribe
      url: /subscribe
      weight: 1
outputs:
  home:
    - HTML
    - RSS
permalinks:
  publ: /:title/
params:
  description: Ben Kitia is a builder; designer & developer in Chicago.
  wordmark: BK
  title: Ben Kitia
  twitter: "@bensonkitiacom"
  icon: https://bensonkitia.com/images/icon.png
  goatCounter: analytics.bensonkitia.com
  mastodon: mastodon.social/@kitia
