backend:
  name: git-gateway
  repo: bensonkitia/bensonkitia.com
  branch: main
collections:
  - name: "writings" # Used in routes, e.g., /admin/collections/blog
    label: "Writings" # Used in the UI
    folder: "content/writings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Categories",
          name: "categories",
          widget: "select",
          options: ["dev & design", "news", "life", "tech"],
          multiple: true,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          add_to_top: false,
          allow_add: true,
          collapsed: false,
          label_singular: "Add tag",
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Content", name: "content", widget: "markdown" }
media_folder: "static/images/uploads"
public_folder: "/images"
publish_mode: editorial_workflow
